# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: StageA
    jobs:
      - job: Curl
        steps:
          - script: curl --fail https://flakeyfunctions.azurewebsites.net/api/randomfail?
            name: "curl1"
            displayName: 'Curl flakey function and fail if 500 error returned'

  - stage: StageB
    dependsOn: StageA
    condition: failed()
    jobs:
      - job: CurlRetry1
        steps:
        - script: curl --fail https://flakeyfunctions.azurewebsites.net/api/randomfail?
          displayName: 'Retry 1'

  - stage: StageContinue
    dependsOn: StageB
    condition: in(dependencies.StageB.result, 'Succeeded', 'Skipped')
    jobs:
      - job: Complete
        steps:
          - script: echo "Congrats one one of 2 attempts you won a 50/50 draw"

