# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: Curl
  steps:
  - script: curl --fail https://flakeyfunctions.azurewebsites.net/api/randomfail?
    name: "curl1"
    displayName: 'Curl flakey function and fail if 500 error returned'
    continueOnError: true

- job: CurlRetry1
  dependsOn: Curl
  condition: failed()
  steps:
  - script: curl --fail https://flakeyfunctions.azurewebsites.net/api/randomfail?
    displayName: 'Retry 1'
    continueOnError: true

- job: CurlRetry2
  dependsOn: CurlRetry1
  condition: failed()
  steps:
  - script: curl --fail https://flakeyfunctions.azurewebsites.net/api/randomfail?
    displayName: 'Retry 2'
    continueOnError: false

- job: Complete
  dependsOn: CurlRetry2
  condition: in(dependencies.CurlRetry2.result, 'Succeeded', 'Skipped')
  steps:
    - script: echo "Congrats one one of 3 attempts you won a 50/50 draw"
